# Generated by Django 2.0.3 on 2018-03-20 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('body', models.CharField(max_length=300)),
                ('blog_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
