# Generated by Django 2.0.3 on 2018-03-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_job_title_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
