# Generated by Django 2.0.3 on 2018-03-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0003_backimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackImage',
        ),
    ]
